//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LifeTrack
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public int Id { get; set; }
        public int AccountId { get; set; }
        public decimal Amount { get; set; }
        public string Payee { get; set; }
        public int CategoryId { get; set; }
        public string Reconciled { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<int> CheckNumber { get; set; }
        public string Memo { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Category Category { get; set; }
    }
}
